version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # For Vite development server (hot reload)
    volumes:
      - ./client:/app
    depends_on:
      - server

  # Node.js Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/rule-engine-db
    volumes:
      - ./server:/app

  # MongoDB Database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

# Define named volumes for MongoDB data persistence
volumes:
  mongo-data:
